// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v7.34.0
// source: nvidia/ai4m/s2s/v1/s2s.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type handleBidiStreamingCall,
  makeGenericClientConstructor,
  type Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Empty } from "../../../../google/protobuf/empty";
import { AudioFormat, audioFormatFromJSON, audioFormatToJSON } from "../../audio/v1/audio";

export const protobufPackage = "nvidia.ai4m.s2s.v1";

/** Possible streaming audio codecs */
export enum StreamingAudioEncoding {
  STREAMING_AUDIO_ENCODING_UNSPECIFIED = 0,
  /** STREAMING_AUDIO_ENCODING_RAW - PCM */
  STREAMING_AUDIO_ENCODING_RAW = 1,
  STREAMING_AUDIO_ENCODING_OPUS = 2,
  UNRECOGNIZED = -1,
}

export function streamingAudioEncodingFromJSON(object: any): StreamingAudioEncoding {
  switch (object) {
    case 0:
    case "STREAMING_AUDIO_ENCODING_UNSPECIFIED":
      return StreamingAudioEncoding.STREAMING_AUDIO_ENCODING_UNSPECIFIED;
    case 1:
    case "STREAMING_AUDIO_ENCODING_RAW":
      return StreamingAudioEncoding.STREAMING_AUDIO_ENCODING_RAW;
    case 2:
    case "STREAMING_AUDIO_ENCODING_OPUS":
      return StreamingAudioEncoding.STREAMING_AUDIO_ENCODING_OPUS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return StreamingAudioEncoding.UNRECOGNIZED;
  }
}

export function streamingAudioEncodingToJSON(object: StreamingAudioEncoding): string {
  switch (object) {
    case StreamingAudioEncoding.STREAMING_AUDIO_ENCODING_UNSPECIFIED:
      return "STREAMING_AUDIO_ENCODING_UNSPECIFIED";
    case StreamingAudioEncoding.STREAMING_AUDIO_ENCODING_RAW:
      return "STREAMING_AUDIO_ENCODING_RAW";
    case StreamingAudioEncoding.STREAMING_AUDIO_ENCODING_OPUS:
      return "STREAMING_AUDIO_ENCODING_OPUS";
    case StreamingAudioEncoding.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** The Audio channel masks (bitmask to represent channel configuration). */
export enum ChannelMask {
  CHANNEL_MASK_UNSPECIFIED = 0,
  /** CHANNEL_MASK_FRONT_LEFT - Mask for front left audio channel. */
  CHANNEL_MASK_FRONT_LEFT = 1,
  /** CHANNEL_MASK_FRONT_RIGHT - Mask for front right audio channel. */
  CHANNEL_MASK_FRONT_RIGHT = 2,
  /**
   * CHANNEL_MASK_2POINT0 - Mask for binaural configuration.
   * CHANNEL_MASK_FRONT_LEFT | CHANNEL_MASK_FRONT_RIGHT
   */
  CHANNEL_MASK_2POINT0 = 3,
  /** CHANNEL_MASK_FRONT_CENTER - Mask for front center audio channel. */
  CHANNEL_MASK_FRONT_CENTER = 4,
  /** CHANNEL_MASK_LOW_FREQUENCY - Mask for low frequency audio channel. */
  CHANNEL_MASK_LOW_FREQUENCY = 8,
  /** CHANNEL_MASK_BACK_LEFT - Mask for back left audio channel. */
  CHANNEL_MASK_BACK_LEFT = 16,
  /** CHANNEL_MASK_BACK_RIGHT - Mask for back right audio channel. */
  CHANNEL_MASK_BACK_RIGHT = 32,
  /**
   * CHANNEL_MASK_QUAD - Mask for quad configuration.
   * CHANNEL_MASK_2POINT0 | CHANNEL_MASK_BACK_LEFT
   *   | CHANNEL_MASK_BACK_RIGHT
   */
  CHANNEL_MASK_QUAD = 51,
  /**
   * CHANNEL_MASK_5POINT1 - Mask for 5.1 configuration.
   * CHANNEL_MASK_QUAD | CHANNEL_MASK_FRONT_CENTER
   *   | CHANNEL_MASK_LOW_FREQUENCY
   */
  CHANNEL_MASK_5POINT1 = 63,
  /** CHANNEL_MASK_FRONT_LEFT_OF_CENTER - Mask for front left of center audio channel. */
  CHANNEL_MASK_FRONT_LEFT_OF_CENTER = 64,
  /** CHANNEL_MASK_FRONT_RIGHT_OF_CENTER - Mask for front right of center audio channel. */
  CHANNEL_MASK_FRONT_RIGHT_OF_CENTER = 128,
  /**
   * CHANNEL_MASK_7POINT1 - Mask for 7.1 configuration.
   * CHANNEL_MASK_5POINT1 | CHANNEL_MASK_FRONT_LEFT_OF_CENTER
   *   | CHANNEL_MASK_FRONT_RIGHT_OF_CENTER
   */
  CHANNEL_MASK_7POINT1 = 255,
  UNRECOGNIZED = -1,
}

export function channelMaskFromJSON(object: any): ChannelMask {
  switch (object) {
    case 0:
    case "CHANNEL_MASK_UNSPECIFIED":
      return ChannelMask.CHANNEL_MASK_UNSPECIFIED;
    case 1:
    case "CHANNEL_MASK_FRONT_LEFT":
      return ChannelMask.CHANNEL_MASK_FRONT_LEFT;
    case 2:
    case "CHANNEL_MASK_FRONT_RIGHT":
      return ChannelMask.CHANNEL_MASK_FRONT_RIGHT;
    case 3:
    case "CHANNEL_MASK_2POINT0":
      return ChannelMask.CHANNEL_MASK_2POINT0;
    case 4:
    case "CHANNEL_MASK_FRONT_CENTER":
      return ChannelMask.CHANNEL_MASK_FRONT_CENTER;
    case 8:
    case "CHANNEL_MASK_LOW_FREQUENCY":
      return ChannelMask.CHANNEL_MASK_LOW_FREQUENCY;
    case 16:
    case "CHANNEL_MASK_BACK_LEFT":
      return ChannelMask.CHANNEL_MASK_BACK_LEFT;
    case 32:
    case "CHANNEL_MASK_BACK_RIGHT":
      return ChannelMask.CHANNEL_MASK_BACK_RIGHT;
    case 51:
    case "CHANNEL_MASK_QUAD":
      return ChannelMask.CHANNEL_MASK_QUAD;
    case 63:
    case "CHANNEL_MASK_5POINT1":
      return ChannelMask.CHANNEL_MASK_5POINT1;
    case 64:
    case "CHANNEL_MASK_FRONT_LEFT_OF_CENTER":
      return ChannelMask.CHANNEL_MASK_FRONT_LEFT_OF_CENTER;
    case 128:
    case "CHANNEL_MASK_FRONT_RIGHT_OF_CENTER":
      return ChannelMask.CHANNEL_MASK_FRONT_RIGHT_OF_CENTER;
    case 255:
    case "CHANNEL_MASK_7POINT1":
      return ChannelMask.CHANNEL_MASK_7POINT1;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ChannelMask.UNRECOGNIZED;
  }
}

export function channelMaskToJSON(object: ChannelMask): string {
  switch (object) {
    case ChannelMask.CHANNEL_MASK_UNSPECIFIED:
      return "CHANNEL_MASK_UNSPECIFIED";
    case ChannelMask.CHANNEL_MASK_FRONT_LEFT:
      return "CHANNEL_MASK_FRONT_LEFT";
    case ChannelMask.CHANNEL_MASK_FRONT_RIGHT:
      return "CHANNEL_MASK_FRONT_RIGHT";
    case ChannelMask.CHANNEL_MASK_2POINT0:
      return "CHANNEL_MASK_2POINT0";
    case ChannelMask.CHANNEL_MASK_FRONT_CENTER:
      return "CHANNEL_MASK_FRONT_CENTER";
    case ChannelMask.CHANNEL_MASK_LOW_FREQUENCY:
      return "CHANNEL_MASK_LOW_FREQUENCY";
    case ChannelMask.CHANNEL_MASK_BACK_LEFT:
      return "CHANNEL_MASK_BACK_LEFT";
    case ChannelMask.CHANNEL_MASK_BACK_RIGHT:
      return "CHANNEL_MASK_BACK_RIGHT";
    case ChannelMask.CHANNEL_MASK_QUAD:
      return "CHANNEL_MASK_QUAD";
    case ChannelMask.CHANNEL_MASK_5POINT1:
      return "CHANNEL_MASK_5POINT1";
    case ChannelMask.CHANNEL_MASK_FRONT_LEFT_OF_CENTER:
      return "CHANNEL_MASK_FRONT_LEFT_OF_CENTER";
    case ChannelMask.CHANNEL_MASK_FRONT_RIGHT_OF_CENTER:
      return "CHANNEL_MASK_FRONT_RIGHT_OF_CENTER";
    case ChannelMask.CHANNEL_MASK_7POINT1:
      return "CHANNEL_MASK_7POINT1";
    case ChannelMask.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Possible Audio layouts */
export enum AudioLayout {
  AUDIO_LAYOUT_UNSPECIFIED = 0,
  AUDIO_LAYOUT_INTERLEAVED = 1,
  AUDIO_LAYOUT_NON_INTERLEAVED = 2,
  UNRECOGNIZED = -1,
}

export function audioLayoutFromJSON(object: any): AudioLayout {
  switch (object) {
    case 0:
    case "AUDIO_LAYOUT_UNSPECIFIED":
      return AudioLayout.AUDIO_LAYOUT_UNSPECIFIED;
    case 1:
    case "AUDIO_LAYOUT_INTERLEAVED":
      return AudioLayout.AUDIO_LAYOUT_INTERLEAVED;
    case 2:
    case "AUDIO_LAYOUT_NON_INTERLEAVED":
      return AudioLayout.AUDIO_LAYOUT_NON_INTERLEAVED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AudioLayout.UNRECOGNIZED;
  }
}

export function audioLayoutToJSON(object: AudioLayout): string {
  switch (object) {
    case AudioLayout.AUDIO_LAYOUT_UNSPECIFIED:
      return "AUDIO_LAYOUT_UNSPECIFIED";
    case AudioLayout.AUDIO_LAYOUT_INTERLEAVED:
      return "AUDIO_LAYOUT_INTERLEAVED";
    case AudioLayout.AUDIO_LAYOUT_NON_INTERLEAVED:
      return "AUDIO_LAYOUT_NON_INTERLEAVED";
    case AudioLayout.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Possible values for Opus Packet loss recovery mechanisms */
export enum OpusLossRecoveryMode {
  OPUS_LOSS_RECOVERY_MODE_UNSPECIFIED = 0,
  /** OPUS_LOSS_RECOVERY_MODE_NONE - This option should be used if no concealment is desired. */
  OPUS_LOSS_RECOVERY_MODE_NONE = 1,
  /** OPUS_LOSS_RECOVERY_MODE_PLC - Use packet loss concealment (PLC). */
  OPUS_LOSS_RECOVERY_MODE_PLC = 2,
  /**
   * OPUS_LOSS_RECOVERY_MODE_FEC - Use in-band forward error correction.
   * Enabling FEC enables PLC as well.
   */
  OPUS_LOSS_RECOVERY_MODE_FEC = 3,
  UNRECOGNIZED = -1,
}

export function opusLossRecoveryModeFromJSON(object: any): OpusLossRecoveryMode {
  switch (object) {
    case 0:
    case "OPUS_LOSS_RECOVERY_MODE_UNSPECIFIED":
      return OpusLossRecoveryMode.OPUS_LOSS_RECOVERY_MODE_UNSPECIFIED;
    case 1:
    case "OPUS_LOSS_RECOVERY_MODE_NONE":
      return OpusLossRecoveryMode.OPUS_LOSS_RECOVERY_MODE_NONE;
    case 2:
    case "OPUS_LOSS_RECOVERY_MODE_PLC":
      return OpusLossRecoveryMode.OPUS_LOSS_RECOVERY_MODE_PLC;
    case 3:
    case "OPUS_LOSS_RECOVERY_MODE_FEC":
      return OpusLossRecoveryMode.OPUS_LOSS_RECOVERY_MODE_FEC;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OpusLossRecoveryMode.UNRECOGNIZED;
  }
}

export function opusLossRecoveryModeToJSON(object: OpusLossRecoveryMode): string {
  switch (object) {
    case OpusLossRecoveryMode.OPUS_LOSS_RECOVERY_MODE_UNSPECIFIED:
      return "OPUS_LOSS_RECOVERY_MODE_UNSPECIFIED";
    case OpusLossRecoveryMode.OPUS_LOSS_RECOVERY_MODE_NONE:
      return "OPUS_LOSS_RECOVERY_MODE_NONE";
    case OpusLossRecoveryMode.OPUS_LOSS_RECOVERY_MODE_PLC:
      return "OPUS_LOSS_RECOVERY_MODE_PLC";
    case OpusLossRecoveryMode.OPUS_LOSS_RECOVERY_MODE_FEC:
      return "OPUS_LOSS_RECOVERY_MODE_FEC";
    case OpusLossRecoveryMode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Configuration which describes streaming Audio properties */
export interface StreamingAudioConfig {
  /** Required: The audio codec */
  encoding: StreamingAudioEncoding;
  /**
   * Required: The sample rate of audio
   * For example: 16000, 48000 etc.
   */
  sample_rate_hz: number;
  /**
   * The configuration which describes the codec setting which are
   * required for a decoder to know. This is set when
   * StreamingAudioConfig corresponds to input audio.
   */
  decoder_config?:
    | AudioDecoderConfig
    | undefined;
  /**
   * The configuration describing the codec setting which are
   * required for an encoder to know. This is set when
   * StreamingAudioConfig corresponds to output audio.
   */
  encoder_config?:
    | AudioEncoderConfig
    | undefined;
  /** The Number of audio channels */
  channels: number;
  /** The Audio channel mask (bitmask to represent channel configuration). */
  channel_mask: ChannelMask;
  /** The audio layout */
  layout: AudioLayout;
  /**
   * The audio chunk duration in milliseconds. When client sends
   * fixed duration frames this value helps NIM for decision making.
   */
  chunk_duration_ms: number;
}

/**
 * The configuration which describes the codec setting which are
 * required for a decoder to know.
 */
export interface AudioDecoderConfig {
  /** Decoder Configuration for STREAMING_AUDIO_ENCODING_RAW */
  raw_dec_config?:
    | RawDecoderConfig
    | undefined;
  /** Decoder Configuration for STREAMING_AUDIO_ENCODING_OPUS */
  opus_dec_config?: OpusDecoderConfig | undefined;
}

/** Decoder Configuration for STREAMING_AUDIO_ENCODING_RAW */
export interface RawDecoderConfig {
  /** Required: The Audio sample Format. */
  format: AudioFormat;
}

/** Decoder Configuration for STREAMING_AUDIO_ENCODING_OPUS */
export interface OpusDecoderConfig {
  /** Opus codec Packet loss recovery mechanism. */
  loss_recovery_mode: OpusLossRecoveryMode;
}

/**
 * The configuration describing the codec setting which are
 * required for an encoder to know.
 */
export interface AudioEncoderConfig {
  /** Encoder Configuration for STREAMING_AUDIO_ENCODING_RAW */
  raw_enc_config?:
    | RawEncoderConfig
    | undefined;
  /** Encoder Configuration for STREAMING_AUDIO_ENCODING_OPUS */
  opus_enc_config?: OpusEncoderConfig | undefined;
}

/** Encoder Configuration for STREAMING_AUDIO_ENCODING_RAW */
export interface RawEncoderConfig {
  /** Required: The Audio sample Format. */
  format: AudioFormat;
}

/** Encoder Configuration for STREAMING_AUDIO_ENCODING_OPUS */
export interface OpusEncoderConfig {
  /** Bitrate (bytes of audio data per second). */
  bitrate: number;
  /**
   * Set if output receiver to leverage FEC (forward error correction)
   * feature of opus encoder.
   */
  use_inband_fec: boolean;
}

/** Configuration message for S2S service */
export interface SpeechToSpeechConfig {
  /** Source language for speech-to-speech translation (e.g., "en", "en-US") */
  source_language?:
    | string
    | undefined;
  /** Target language for speech-to-speech translation (e.g., "es", "es-US") */
  target_language?:
    | string
    | undefined;
  /**
   * Voice name for TTS (optional, service will use default if not provided)
   * For zero-shot TTS (transactional mode), the service automatically extracts
   * the first 10 seconds of input audio as the voice reference
   */
  voice_name?:
    | string
    | undefined;
  /** Number of speakers to detect. 0 = auto-detect (ElevenLabs API default). */
  elevenlabs_num_speakers?:
    | number
    | undefined;
  /** Whether to drop background audio from the final dub. */
  elevenlabs_drop_background_audio?:
    | boolean
    | undefined;
  /** [BETA] Whether transcripts should have profanities censored. */
  elevenlabs_use_profanity_filter?:
    | boolean
    | undefined;
  /** [Experimental] Accent to apply when selecting voices and translating. */
  elevenlabs_target_accent?:
    | string
    | undefined;
  /** Whether to use the highest resolution available. */
  elevenlabs_highest_resolution?:
    | boolean
    | undefined;
  /** Whether to apply watermark to the output. */
  elevenlabs_watermark?:
    | boolean
    | undefined;
  /** Whether to prepare dub for edits in dubbing studio. */
  elevenlabs_dubbing_studio?: boolean | undefined;
}

/** S2S message containing audio data and metadata */
export interface SpeechToSpeechRequest {
  /** Raw audio data */
  audio_data?:
    | Uint8Array
    | undefined;
  /** Sample rate of the audio (default: 16000) */
  audio_sample_rate?:
    | number
    | undefined;
  /** Number of channels (1 for mono, 2 for stereo) (default: 1) */
  audio_num_channels?:
    | number
    | undefined;
  /** Audio format (e.g., "WAV", "LINEAR_PCM", "MP#") (default: "LINEAR_PCM") */
  audio_format?:
    | string
    | undefined;
  /** Configuration for S2S service (should be sent as first message) */
  config?:
    | SpeechToSpeechConfig
    | undefined;
  /**
   * Optionally adding audio config parmaters
   * TODO: This needs to be added to an inference config at the begining of inference instead
   * of during request. Adding this is going to require a change to the service itself
   * and will be taken up in the future.
   */
  audio_config?: StreamingAudioConfig | undefined;
}

/** S2S message containing audio data and metadata */
export interface SpeechToSpeechResponse {
  /** Raw audio data */
  audio_data?:
    | Uint8Array
    | undefined;
  /** Sample rate of the audio (default: 16000) */
  audio_sample_rate?:
    | number
    | undefined;
  /** Number of channels (1 for mono, 2 for stereo) (default: 1) */
  audio_num_channels?:
    | number
    | undefined;
  /** Audio format (e.g., "wav", "pcm") (default: "mp3") */
  audio_format?:
    | string
    | undefined;
  /** Empty message used to maintain connection (keep-alive) */
  keepalive?: Empty | undefined;
}

function createBaseStreamingAudioConfig(): StreamingAudioConfig {
  return {
    encoding: 0,
    sample_rate_hz: 0,
    decoder_config: undefined,
    encoder_config: undefined,
    channels: 0,
    channel_mask: 0,
    layout: 0,
    chunk_duration_ms: 0,
  };
}

export const StreamingAudioConfig: MessageFns<StreamingAudioConfig> = {
  encode(message: StreamingAudioConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.encoding !== 0) {
      writer.uint32(8).int32(message.encoding);
    }
    if (message.sample_rate_hz !== 0) {
      writer.uint32(16).uint32(message.sample_rate_hz);
    }
    if (message.decoder_config !== undefined) {
      AudioDecoderConfig.encode(message.decoder_config, writer.uint32(26).fork()).join();
    }
    if (message.encoder_config !== undefined) {
      AudioEncoderConfig.encode(message.encoder_config, writer.uint32(34).fork()).join();
    }
    if (message.channels !== 0) {
      writer.uint32(40).uint32(message.channels);
    }
    if (message.channel_mask !== 0) {
      writer.uint32(48).int32(message.channel_mask);
    }
    if (message.layout !== 0) {
      writer.uint32(56).int32(message.layout);
    }
    if (message.chunk_duration_ms !== 0) {
      writer.uint32(64).uint32(message.chunk_duration_ms);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamingAudioConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamingAudioConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.encoding = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.sample_rate_hz = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.decoder_config = AudioDecoderConfig.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.encoder_config = AudioEncoderConfig.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.channels = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.channel_mask = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.layout = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.chunk_duration_ms = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamingAudioConfig {
    return {
      encoding: isSet(object.encoding) ? streamingAudioEncodingFromJSON(object.encoding) : 0,
      sample_rate_hz: isSet(object.sample_rate_hz) ? globalThis.Number(object.sample_rate_hz) : 0,
      decoder_config: isSet(object.decoder_config) ? AudioDecoderConfig.fromJSON(object.decoder_config) : undefined,
      encoder_config: isSet(object.encoder_config) ? AudioEncoderConfig.fromJSON(object.encoder_config) : undefined,
      channels: isSet(object.channels) ? globalThis.Number(object.channels) : 0,
      channel_mask: isSet(object.channel_mask) ? channelMaskFromJSON(object.channel_mask) : 0,
      layout: isSet(object.layout) ? audioLayoutFromJSON(object.layout) : 0,
      chunk_duration_ms: isSet(object.chunk_duration_ms) ? globalThis.Number(object.chunk_duration_ms) : 0,
    };
  },

  toJSON(message: StreamingAudioConfig): unknown {
    const obj: any = {};
    if (message.encoding !== 0) {
      obj.encoding = streamingAudioEncodingToJSON(message.encoding);
    }
    if (message.sample_rate_hz !== 0) {
      obj.sample_rate_hz = Math.round(message.sample_rate_hz);
    }
    if (message.decoder_config !== undefined) {
      obj.decoder_config = AudioDecoderConfig.toJSON(message.decoder_config);
    }
    if (message.encoder_config !== undefined) {
      obj.encoder_config = AudioEncoderConfig.toJSON(message.encoder_config);
    }
    if (message.channels !== 0) {
      obj.channels = Math.round(message.channels);
    }
    if (message.channel_mask !== 0) {
      obj.channel_mask = channelMaskToJSON(message.channel_mask);
    }
    if (message.layout !== 0) {
      obj.layout = audioLayoutToJSON(message.layout);
    }
    if (message.chunk_duration_ms !== 0) {
      obj.chunk_duration_ms = Math.round(message.chunk_duration_ms);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamingAudioConfig>, I>>(base?: I): StreamingAudioConfig {
    return StreamingAudioConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamingAudioConfig>, I>>(object: I): StreamingAudioConfig {
    const message = createBaseStreamingAudioConfig();
    message.encoding = object.encoding ?? 0;
    message.sample_rate_hz = object.sample_rate_hz ?? 0;
    message.decoder_config = (object.decoder_config !== undefined && object.decoder_config !== null)
      ? AudioDecoderConfig.fromPartial(object.decoder_config)
      : undefined;
    message.encoder_config = (object.encoder_config !== undefined && object.encoder_config !== null)
      ? AudioEncoderConfig.fromPartial(object.encoder_config)
      : undefined;
    message.channels = object.channels ?? 0;
    message.channel_mask = object.channel_mask ?? 0;
    message.layout = object.layout ?? 0;
    message.chunk_duration_ms = object.chunk_duration_ms ?? 0;
    return message;
  },
};

function createBaseAudioDecoderConfig(): AudioDecoderConfig {
  return { raw_dec_config: undefined, opus_dec_config: undefined };
}

export const AudioDecoderConfig: MessageFns<AudioDecoderConfig> = {
  encode(message: AudioDecoderConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.raw_dec_config !== undefined) {
      RawDecoderConfig.encode(message.raw_dec_config, writer.uint32(10).fork()).join();
    }
    if (message.opus_dec_config !== undefined) {
      OpusDecoderConfig.encode(message.opus_dec_config, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AudioDecoderConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAudioDecoderConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.raw_dec_config = RawDecoderConfig.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.opus_dec_config = OpusDecoderConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AudioDecoderConfig {
    return {
      raw_dec_config: isSet(object.raw_dec_config) ? RawDecoderConfig.fromJSON(object.raw_dec_config) : undefined,
      opus_dec_config: isSet(object.opus_dec_config) ? OpusDecoderConfig.fromJSON(object.opus_dec_config) : undefined,
    };
  },

  toJSON(message: AudioDecoderConfig): unknown {
    const obj: any = {};
    if (message.raw_dec_config !== undefined) {
      obj.raw_dec_config = RawDecoderConfig.toJSON(message.raw_dec_config);
    }
    if (message.opus_dec_config !== undefined) {
      obj.opus_dec_config = OpusDecoderConfig.toJSON(message.opus_dec_config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AudioDecoderConfig>, I>>(base?: I): AudioDecoderConfig {
    return AudioDecoderConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioDecoderConfig>, I>>(object: I): AudioDecoderConfig {
    const message = createBaseAudioDecoderConfig();
    message.raw_dec_config = (object.raw_dec_config !== undefined && object.raw_dec_config !== null)
      ? RawDecoderConfig.fromPartial(object.raw_dec_config)
      : undefined;
    message.opus_dec_config = (object.opus_dec_config !== undefined && object.opus_dec_config !== null)
      ? OpusDecoderConfig.fromPartial(object.opus_dec_config)
      : undefined;
    return message;
  },
};

function createBaseRawDecoderConfig(): RawDecoderConfig {
  return { format: 0 };
}

export const RawDecoderConfig: MessageFns<RawDecoderConfig> = {
  encode(message: RawDecoderConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.format !== 0) {
      writer.uint32(8).int32(message.format);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RawDecoderConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRawDecoderConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.format = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RawDecoderConfig {
    return { format: isSet(object.format) ? audioFormatFromJSON(object.format) : 0 };
  },

  toJSON(message: RawDecoderConfig): unknown {
    const obj: any = {};
    if (message.format !== 0) {
      obj.format = audioFormatToJSON(message.format);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RawDecoderConfig>, I>>(base?: I): RawDecoderConfig {
    return RawDecoderConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RawDecoderConfig>, I>>(object: I): RawDecoderConfig {
    const message = createBaseRawDecoderConfig();
    message.format = object.format ?? 0;
    return message;
  },
};

function createBaseOpusDecoderConfig(): OpusDecoderConfig {
  return { loss_recovery_mode: 0 };
}

export const OpusDecoderConfig: MessageFns<OpusDecoderConfig> = {
  encode(message: OpusDecoderConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.loss_recovery_mode !== 0) {
      writer.uint32(8).int32(message.loss_recovery_mode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpusDecoderConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOpusDecoderConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.loss_recovery_mode = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OpusDecoderConfig {
    return {
      loss_recovery_mode: isSet(object.loss_recovery_mode)
        ? opusLossRecoveryModeFromJSON(object.loss_recovery_mode)
        : 0,
    };
  },

  toJSON(message: OpusDecoderConfig): unknown {
    const obj: any = {};
    if (message.loss_recovery_mode !== 0) {
      obj.loss_recovery_mode = opusLossRecoveryModeToJSON(message.loss_recovery_mode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OpusDecoderConfig>, I>>(base?: I): OpusDecoderConfig {
    return OpusDecoderConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OpusDecoderConfig>, I>>(object: I): OpusDecoderConfig {
    const message = createBaseOpusDecoderConfig();
    message.loss_recovery_mode = object.loss_recovery_mode ?? 0;
    return message;
  },
};

function createBaseAudioEncoderConfig(): AudioEncoderConfig {
  return { raw_enc_config: undefined, opus_enc_config: undefined };
}

export const AudioEncoderConfig: MessageFns<AudioEncoderConfig> = {
  encode(message: AudioEncoderConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.raw_enc_config !== undefined) {
      RawEncoderConfig.encode(message.raw_enc_config, writer.uint32(10).fork()).join();
    }
    if (message.opus_enc_config !== undefined) {
      OpusEncoderConfig.encode(message.opus_enc_config, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AudioEncoderConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAudioEncoderConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.raw_enc_config = RawEncoderConfig.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.opus_enc_config = OpusEncoderConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AudioEncoderConfig {
    return {
      raw_enc_config: isSet(object.raw_enc_config) ? RawEncoderConfig.fromJSON(object.raw_enc_config) : undefined,
      opus_enc_config: isSet(object.opus_enc_config) ? OpusEncoderConfig.fromJSON(object.opus_enc_config) : undefined,
    };
  },

  toJSON(message: AudioEncoderConfig): unknown {
    const obj: any = {};
    if (message.raw_enc_config !== undefined) {
      obj.raw_enc_config = RawEncoderConfig.toJSON(message.raw_enc_config);
    }
    if (message.opus_enc_config !== undefined) {
      obj.opus_enc_config = OpusEncoderConfig.toJSON(message.opus_enc_config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AudioEncoderConfig>, I>>(base?: I): AudioEncoderConfig {
    return AudioEncoderConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AudioEncoderConfig>, I>>(object: I): AudioEncoderConfig {
    const message = createBaseAudioEncoderConfig();
    message.raw_enc_config = (object.raw_enc_config !== undefined && object.raw_enc_config !== null)
      ? RawEncoderConfig.fromPartial(object.raw_enc_config)
      : undefined;
    message.opus_enc_config = (object.opus_enc_config !== undefined && object.opus_enc_config !== null)
      ? OpusEncoderConfig.fromPartial(object.opus_enc_config)
      : undefined;
    return message;
  },
};

function createBaseRawEncoderConfig(): RawEncoderConfig {
  return { format: 0 };
}

export const RawEncoderConfig: MessageFns<RawEncoderConfig> = {
  encode(message: RawEncoderConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.format !== 0) {
      writer.uint32(8).int32(message.format);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RawEncoderConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRawEncoderConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.format = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RawEncoderConfig {
    return { format: isSet(object.format) ? audioFormatFromJSON(object.format) : 0 };
  },

  toJSON(message: RawEncoderConfig): unknown {
    const obj: any = {};
    if (message.format !== 0) {
      obj.format = audioFormatToJSON(message.format);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RawEncoderConfig>, I>>(base?: I): RawEncoderConfig {
    return RawEncoderConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RawEncoderConfig>, I>>(object: I): RawEncoderConfig {
    const message = createBaseRawEncoderConfig();
    message.format = object.format ?? 0;
    return message;
  },
};

function createBaseOpusEncoderConfig(): OpusEncoderConfig {
  return { bitrate: 0, use_inband_fec: false };
}

export const OpusEncoderConfig: MessageFns<OpusEncoderConfig> = {
  encode(message: OpusEncoderConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bitrate !== 0) {
      writer.uint32(8).uint32(message.bitrate);
    }
    if (message.use_inband_fec !== false) {
      writer.uint32(16).bool(message.use_inband_fec);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpusEncoderConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOpusEncoderConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bitrate = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.use_inband_fec = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OpusEncoderConfig {
    return {
      bitrate: isSet(object.bitrate) ? globalThis.Number(object.bitrate) : 0,
      use_inband_fec: isSet(object.use_inband_fec) ? globalThis.Boolean(object.use_inband_fec) : false,
    };
  },

  toJSON(message: OpusEncoderConfig): unknown {
    const obj: any = {};
    if (message.bitrate !== 0) {
      obj.bitrate = Math.round(message.bitrate);
    }
    if (message.use_inband_fec !== false) {
      obj.use_inband_fec = message.use_inband_fec;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OpusEncoderConfig>, I>>(base?: I): OpusEncoderConfig {
    return OpusEncoderConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OpusEncoderConfig>, I>>(object: I): OpusEncoderConfig {
    const message = createBaseOpusEncoderConfig();
    message.bitrate = object.bitrate ?? 0;
    message.use_inband_fec = object.use_inband_fec ?? false;
    return message;
  },
};

function createBaseSpeechToSpeechConfig(): SpeechToSpeechConfig {
  return {
    source_language: undefined,
    target_language: undefined,
    voice_name: undefined,
    elevenlabs_num_speakers: undefined,
    elevenlabs_drop_background_audio: undefined,
    elevenlabs_use_profanity_filter: undefined,
    elevenlabs_target_accent: undefined,
    elevenlabs_highest_resolution: undefined,
    elevenlabs_watermark: undefined,
    elevenlabs_dubbing_studio: undefined,
  };
}

export const SpeechToSpeechConfig: MessageFns<SpeechToSpeechConfig> = {
  encode(message: SpeechToSpeechConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.source_language !== undefined) {
      writer.uint32(10).string(message.source_language);
    }
    if (message.target_language !== undefined) {
      writer.uint32(18).string(message.target_language);
    }
    if (message.voice_name !== undefined) {
      writer.uint32(26).string(message.voice_name);
    }
    if (message.elevenlabs_num_speakers !== undefined) {
      writer.uint32(32).int32(message.elevenlabs_num_speakers);
    }
    if (message.elevenlabs_drop_background_audio !== undefined) {
      writer.uint32(40).bool(message.elevenlabs_drop_background_audio);
    }
    if (message.elevenlabs_use_profanity_filter !== undefined) {
      writer.uint32(48).bool(message.elevenlabs_use_profanity_filter);
    }
    if (message.elevenlabs_target_accent !== undefined) {
      writer.uint32(58).string(message.elevenlabs_target_accent);
    }
    if (message.elevenlabs_highest_resolution !== undefined) {
      writer.uint32(64).bool(message.elevenlabs_highest_resolution);
    }
    if (message.elevenlabs_watermark !== undefined) {
      writer.uint32(72).bool(message.elevenlabs_watermark);
    }
    if (message.elevenlabs_dubbing_studio !== undefined) {
      writer.uint32(80).bool(message.elevenlabs_dubbing_studio);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpeechToSpeechConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpeechToSpeechConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.source_language = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.target_language = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.voice_name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.elevenlabs_num_speakers = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.elevenlabs_drop_background_audio = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.elevenlabs_use_profanity_filter = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.elevenlabs_target_accent = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.elevenlabs_highest_resolution = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.elevenlabs_watermark = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.elevenlabs_dubbing_studio = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpeechToSpeechConfig {
    return {
      source_language: isSet(object.source_language) ? globalThis.String(object.source_language) : undefined,
      target_language: isSet(object.target_language) ? globalThis.String(object.target_language) : undefined,
      voice_name: isSet(object.voice_name) ? globalThis.String(object.voice_name) : undefined,
      elevenlabs_num_speakers: isSet(object.elevenlabs_num_speakers)
        ? globalThis.Number(object.elevenlabs_num_speakers)
        : undefined,
      elevenlabs_drop_background_audio: isSet(object.elevenlabs_drop_background_audio)
        ? globalThis.Boolean(object.elevenlabs_drop_background_audio)
        : undefined,
      elevenlabs_use_profanity_filter: isSet(object.elevenlabs_use_profanity_filter)
        ? globalThis.Boolean(object.elevenlabs_use_profanity_filter)
        : undefined,
      elevenlabs_target_accent: isSet(object.elevenlabs_target_accent)
        ? globalThis.String(object.elevenlabs_target_accent)
        : undefined,
      elevenlabs_highest_resolution: isSet(object.elevenlabs_highest_resolution)
        ? globalThis.Boolean(object.elevenlabs_highest_resolution)
        : undefined,
      elevenlabs_watermark: isSet(object.elevenlabs_watermark)
        ? globalThis.Boolean(object.elevenlabs_watermark)
        : undefined,
      elevenlabs_dubbing_studio: isSet(object.elevenlabs_dubbing_studio)
        ? globalThis.Boolean(object.elevenlabs_dubbing_studio)
        : undefined,
    };
  },

  toJSON(message: SpeechToSpeechConfig): unknown {
    const obj: any = {};
    if (message.source_language !== undefined) {
      obj.source_language = message.source_language;
    }
    if (message.target_language !== undefined) {
      obj.target_language = message.target_language;
    }
    if (message.voice_name !== undefined) {
      obj.voice_name = message.voice_name;
    }
    if (message.elevenlabs_num_speakers !== undefined) {
      obj.elevenlabs_num_speakers = Math.round(message.elevenlabs_num_speakers);
    }
    if (message.elevenlabs_drop_background_audio !== undefined) {
      obj.elevenlabs_drop_background_audio = message.elevenlabs_drop_background_audio;
    }
    if (message.elevenlabs_use_profanity_filter !== undefined) {
      obj.elevenlabs_use_profanity_filter = message.elevenlabs_use_profanity_filter;
    }
    if (message.elevenlabs_target_accent !== undefined) {
      obj.elevenlabs_target_accent = message.elevenlabs_target_accent;
    }
    if (message.elevenlabs_highest_resolution !== undefined) {
      obj.elevenlabs_highest_resolution = message.elevenlabs_highest_resolution;
    }
    if (message.elevenlabs_watermark !== undefined) {
      obj.elevenlabs_watermark = message.elevenlabs_watermark;
    }
    if (message.elevenlabs_dubbing_studio !== undefined) {
      obj.elevenlabs_dubbing_studio = message.elevenlabs_dubbing_studio;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpeechToSpeechConfig>, I>>(base?: I): SpeechToSpeechConfig {
    return SpeechToSpeechConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpeechToSpeechConfig>, I>>(object: I): SpeechToSpeechConfig {
    const message = createBaseSpeechToSpeechConfig();
    message.source_language = object.source_language ?? undefined;
    message.target_language = object.target_language ?? undefined;
    message.voice_name = object.voice_name ?? undefined;
    message.elevenlabs_num_speakers = object.elevenlabs_num_speakers ?? undefined;
    message.elevenlabs_drop_background_audio = object.elevenlabs_drop_background_audio ?? undefined;
    message.elevenlabs_use_profanity_filter = object.elevenlabs_use_profanity_filter ?? undefined;
    message.elevenlabs_target_accent = object.elevenlabs_target_accent ?? undefined;
    message.elevenlabs_highest_resolution = object.elevenlabs_highest_resolution ?? undefined;
    message.elevenlabs_watermark = object.elevenlabs_watermark ?? undefined;
    message.elevenlabs_dubbing_studio = object.elevenlabs_dubbing_studio ?? undefined;
    return message;
  },
};

function createBaseSpeechToSpeechRequest(): SpeechToSpeechRequest {
  return {
    audio_data: undefined,
    audio_sample_rate: undefined,
    audio_num_channels: undefined,
    audio_format: undefined,
    config: undefined,
    audio_config: undefined,
  };
}

export const SpeechToSpeechRequest: MessageFns<SpeechToSpeechRequest> = {
  encode(message: SpeechToSpeechRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.audio_data !== undefined) {
      writer.uint32(10).bytes(message.audio_data);
    }
    if (message.audio_sample_rate !== undefined) {
      writer.uint32(24).int32(message.audio_sample_rate);
    }
    if (message.audio_num_channels !== undefined) {
      writer.uint32(32).int32(message.audio_num_channels);
    }
    if (message.audio_format !== undefined) {
      writer.uint32(42).string(message.audio_format);
    }
    if (message.config !== undefined) {
      SpeechToSpeechConfig.encode(message.config, writer.uint32(50).fork()).join();
    }
    if (message.audio_config !== undefined) {
      StreamingAudioConfig.encode(message.audio_config, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpeechToSpeechRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpeechToSpeechRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.audio_data = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.audio_sample_rate = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.audio_num_channels = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.audio_format = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.config = SpeechToSpeechConfig.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.audio_config = StreamingAudioConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpeechToSpeechRequest {
    return {
      audio_data: isSet(object.audio_data) ? bytesFromBase64(object.audio_data) : undefined,
      audio_sample_rate: isSet(object.audio_sample_rate) ? globalThis.Number(object.audio_sample_rate) : undefined,
      audio_num_channels: isSet(object.audio_num_channels) ? globalThis.Number(object.audio_num_channels) : undefined,
      audio_format: isSet(object.audio_format) ? globalThis.String(object.audio_format) : undefined,
      config: isSet(object.config) ? SpeechToSpeechConfig.fromJSON(object.config) : undefined,
      audio_config: isSet(object.audio_config) ? StreamingAudioConfig.fromJSON(object.audio_config) : undefined,
    };
  },

  toJSON(message: SpeechToSpeechRequest): unknown {
    const obj: any = {};
    if (message.audio_data !== undefined) {
      obj.audio_data = base64FromBytes(message.audio_data);
    }
    if (message.audio_sample_rate !== undefined) {
      obj.audio_sample_rate = Math.round(message.audio_sample_rate);
    }
    if (message.audio_num_channels !== undefined) {
      obj.audio_num_channels = Math.round(message.audio_num_channels);
    }
    if (message.audio_format !== undefined) {
      obj.audio_format = message.audio_format;
    }
    if (message.config !== undefined) {
      obj.config = SpeechToSpeechConfig.toJSON(message.config);
    }
    if (message.audio_config !== undefined) {
      obj.audio_config = StreamingAudioConfig.toJSON(message.audio_config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpeechToSpeechRequest>, I>>(base?: I): SpeechToSpeechRequest {
    return SpeechToSpeechRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpeechToSpeechRequest>, I>>(object: I): SpeechToSpeechRequest {
    const message = createBaseSpeechToSpeechRequest();
    message.audio_data = object.audio_data ?? undefined;
    message.audio_sample_rate = object.audio_sample_rate ?? undefined;
    message.audio_num_channels = object.audio_num_channels ?? undefined;
    message.audio_format = object.audio_format ?? undefined;
    message.config = (object.config !== undefined && object.config !== null)
      ? SpeechToSpeechConfig.fromPartial(object.config)
      : undefined;
    message.audio_config = (object.audio_config !== undefined && object.audio_config !== null)
      ? StreamingAudioConfig.fromPartial(object.audio_config)
      : undefined;
    return message;
  },
};

function createBaseSpeechToSpeechResponse(): SpeechToSpeechResponse {
  return {
    audio_data: undefined,
    audio_sample_rate: undefined,
    audio_num_channels: undefined,
    audio_format: undefined,
    keepalive: undefined,
  };
}

export const SpeechToSpeechResponse: MessageFns<SpeechToSpeechResponse> = {
  encode(message: SpeechToSpeechResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.audio_data !== undefined) {
      writer.uint32(10).bytes(message.audio_data);
    }
    if (message.audio_sample_rate !== undefined) {
      writer.uint32(32).int32(message.audio_sample_rate);
    }
    if (message.audio_num_channels !== undefined) {
      writer.uint32(40).int32(message.audio_num_channels);
    }
    if (message.audio_format !== undefined) {
      writer.uint32(50).string(message.audio_format);
    }
    if (message.keepalive !== undefined) {
      Empty.encode(message.keepalive, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SpeechToSpeechResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSpeechToSpeechResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.audio_data = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.audio_sample_rate = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.audio_num_channels = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.audio_format = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.keepalive = Empty.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SpeechToSpeechResponse {
    return {
      audio_data: isSet(object.audio_data) ? bytesFromBase64(object.audio_data) : undefined,
      audio_sample_rate: isSet(object.audio_sample_rate) ? globalThis.Number(object.audio_sample_rate) : undefined,
      audio_num_channels: isSet(object.audio_num_channels) ? globalThis.Number(object.audio_num_channels) : undefined,
      audio_format: isSet(object.audio_format) ? globalThis.String(object.audio_format) : undefined,
      keepalive: isSet(object.keepalive) ? Empty.fromJSON(object.keepalive) : undefined,
    };
  },

  toJSON(message: SpeechToSpeechResponse): unknown {
    const obj: any = {};
    if (message.audio_data !== undefined) {
      obj.audio_data = base64FromBytes(message.audio_data);
    }
    if (message.audio_sample_rate !== undefined) {
      obj.audio_sample_rate = Math.round(message.audio_sample_rate);
    }
    if (message.audio_num_channels !== undefined) {
      obj.audio_num_channels = Math.round(message.audio_num_channels);
    }
    if (message.audio_format !== undefined) {
      obj.audio_format = message.audio_format;
    }
    if (message.keepalive !== undefined) {
      obj.keepalive = Empty.toJSON(message.keepalive);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SpeechToSpeechResponse>, I>>(base?: I): SpeechToSpeechResponse {
    return SpeechToSpeechResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SpeechToSpeechResponse>, I>>(object: I): SpeechToSpeechResponse {
    const message = createBaseSpeechToSpeechResponse();
    message.audio_data = object.audio_data ?? undefined;
    message.audio_sample_rate = object.audio_sample_rate ?? undefined;
    message.audio_num_channels = object.audio_num_channels ?? undefined;
    message.audio_format = object.audio_format ?? undefined;
    message.keepalive = (object.keepalive !== undefined && object.keepalive !== null)
      ? Empty.fromPartial(object.keepalive)
      : undefined;
    return message;
  },
};

/** Speech to Speech service definition */
export type SpeechToSpeechService = typeof SpeechToSpeechService;
export const SpeechToSpeechService = {
  /** Bidirectional streaming RPC for speech-to-speech conversion */
  streamSpeechToSpeech: {
    path: "/nvidia.ai4m.s2s.v1.SpeechToSpeech/StreamSpeechToSpeech",
    requestStream: true,
    responseStream: true,
    requestSerialize: (value: SpeechToSpeechRequest): Buffer =>
      Buffer.from(SpeechToSpeechRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SpeechToSpeechRequest => SpeechToSpeechRequest.decode(value),
    responseSerialize: (value: SpeechToSpeechResponse): Buffer =>
      Buffer.from(SpeechToSpeechResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SpeechToSpeechResponse => SpeechToSpeechResponse.decode(value),
  },
} as const;

export interface SpeechToSpeechServer extends UntypedServiceImplementation {
  /** Bidirectional streaming RPC for speech-to-speech conversion */
  streamSpeechToSpeech: handleBidiStreamingCall<SpeechToSpeechRequest, SpeechToSpeechResponse>;
}

export interface SpeechToSpeechClient extends Client {
  /** Bidirectional streaming RPC for speech-to-speech conversion */
  streamSpeechToSpeech(): ClientDuplexStream<SpeechToSpeechRequest, SpeechToSpeechResponse>;
  streamSpeechToSpeech(
    options: Partial<CallOptions>,
  ): ClientDuplexStream<SpeechToSpeechRequest, SpeechToSpeechResponse>;
  streamSpeechToSpeech(
    metadata: Metadata,
    options?: Partial<CallOptions>,
  ): ClientDuplexStream<SpeechToSpeechRequest, SpeechToSpeechResponse>;
}

export const SpeechToSpeechClient = makeGenericClientConstructor(
  SpeechToSpeechService,
  "nvidia.ai4m.s2s.v1.SpeechToSpeech",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): SpeechToSpeechClient;
  service: typeof SpeechToSpeechService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
